# Generated by Django 2.2.4 on 2020-04-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_book_app', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite',
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_uploaded', to='favorite_book_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(null=True, related_name='liked_book', to='favorite_book_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='books_uploaded',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_books',
            field=models.IntegerField(null=True),
        ),
    ]
