# Generated by Django 2.2.4 on 2020-04-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_book_app', '0003_auto_20200427_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_book', to='favorite_book_app.User'),
        ),
    ]
