# Generated by Django 2.2.4 on 2020-04-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_book_app', '0004_auto_20200427_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_who_like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books_uploaded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_books',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_like', to='favorite_book_app.Book')),
                ('u_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='favorite_book_app.User')),
            ],
        ),
    ]
