# Generated by Django 2.2.4 on 2020-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('winRate', models.FloatField(max_length=6)),
                ('pickRate', models.FloatField(max_length=6)),
                ('banRate', models.FloatField(max_length=6)),
                ('champClass', models.CharField(max_length=255)),
                ('champType', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
